<?php

namespace Dope\ClassifierBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Dope\ClassifierBundle\Entity\TrainParameterClassResult;

/**
 * TrainParameterClassResultRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method TrainParameterClassResult find($id, $lockMode = null, $lockVersion = null)
 * @method TrainParameterClassResult[] findAll()
 * @method TrainParameterClassResult[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 * @method TrainParameterClassResult findOneBy(array $criteria, array $orderBy = null)
 */
class TrainParameterClassResultRepository extends EntityRepository
{
}
