<?php

namespace Dope\ClassifierBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Dope\ClassifierBundle\Entity\TrainParameterResult;

/**
 * TrainParameterResultRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method TrainParameterResult find($id, $lockMode = null, $lockVersion = null)
 * @method TrainParameterResult[] findAll()
 * @method TrainParameterResult[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 * @method TrainParameterResult findOneBy(array $criteria, array $orderBy = null)
 */
class TrainParameterResultRepository extends EntityRepository
{
    /**
     * @param TrainParameterResult $entity
     */
    public function add(TrainParameterResult $entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
    }
}
